type = "Component"
display_name = "Plugins: Active checks (cmk)"
has_support_component = true
members_required = 1
description = """
Most of the active checks that are maintained
by Checkmk (as opposed to integrations for the
'monitoring plugins'.

Some active checks may belong to dedicated integrations
(like elasticsearch).
"""
