type = "Component"
display_name = "Plugins: Active checks (monitoring-plugins)"
has_support_component = true
members_required = 1
description = """
Integration of the active checks provided by
the third party `monitoring-plugins`.
(as opposed to active checks maintained by Checkmk).
"""
